apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: registry.cn-hangzhou.aliyuncs.com/k8sarm64/pause:3.1 
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
imageRepository: registry.cn-hangzhou.aliyuncs.com/k8sarm64 
kubernetesVersion: v1.13.3
networking:
  podSubnet: 10.244.0.0/16
